version: '2'

services:
  db:
    image: postgres:10.3-alpine

  ci:
    build: .
    depends_on:
      - db
    environment:
      COVERAGE: true
      RAILS_ENV: test
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
    volumes:
      - .:/task_manager
    command: sh -c "bundle exec rails db:prepare && bundle exec rake test"